# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppms_invoice_client\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reference_combo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_combo.sizePolicy().hasHeightForWidth())
        self.reference_combo.setSizePolicy(sizePolicy)
        self.reference_combo.setObjectName("reference_combo")
        self.horizontalLayout.addWidget(self.reference_combo)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.autonomous_tab = QtWidgets.QWidget()
        self.autonomous_tab.setObjectName("autonomous_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.autonomous_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.auto_table = QtWidgets.QTableWidget(self.autonomous_tab)
        self.auto_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.auto_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.auto_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.auto_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.auto_table.setColumnCount(9)
        self.auto_table.setObjectName("auto_table")
        self.auto_table.setRowCount(0)
        self.gridLayout.addWidget(self.auto_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.autonomous_tab, "")
        self.assisted_tab = QtWidgets.QWidget()
        self.assisted_tab.setObjectName("assisted_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.assisted_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.assist_table = QtWidgets.QTableWidget(self.assisted_tab)
        self.assist_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.assist_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.assist_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.assist_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.assist_table.setColumnCount(9)
        self.assist_table.setObjectName("assist_table")
        self.assist_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.assist_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.assisted_tab, "")
        self.training_tab = QtWidgets.QWidget()
        self.training_tab.setObjectName("training_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.training_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.train_table = QtWidgets.QTableWidget(self.training_tab)
        self.train_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.train_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.train_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.train_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.train_table.setColumnCount(9)
        self.train_table.setObjectName("train_table")
        self.train_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.train_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.training_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout_2.addWidget(self.select_btn)
        self.deselect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.deselect_btn.setObjectName("deselect_btn")
        self.horizontalLayout_2.addWidget(self.deselect_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sendto_combo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendto_combo.sizePolicy().hasHeightForWidth())
        self.sendto_combo.setSizePolicy(sizePolicy)
        self.sendto_combo.setObjectName("sendto_combo")
        self.sendto_combo.addItem("")
        self.sendto_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.sendto_combo)
        self.copy_chk = QtWidgets.QCheckBox(self.centralwidget)
        self.copy_chk.setObjectName("copy_chk")
        self.horizontalLayout_2.addWidget(self.copy_chk)
        self.email_button = QtWidgets.QPushButton(self.centralwidget)
        self.email_button.setObjectName("email_button")
        self.horizontalLayout_2.addWidget(self.email_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPPMS = QtWidgets.QAction(MainWindow)
        self.actionPPMS.setObjectName("actionPPMS")
        self.actionEmail = QtWidgets.QAction(MainWindow)
        self.actionEmail.setObjectName("actionEmail")
        self.actionInvoice_template = QtWidgets.QAction(MainWindow)
        self.actionInvoice_template.setObjectName("actionInvoice_template")
        self.actionFacility = QtWidgets.QAction(MainWindow)
        self.actionFacility.setObjectName("actionFacility")
        self.actionGeneral = QtWidgets.QAction(MainWindow)
        self.actionGeneral.setObjectName("actionGeneral")
        self.menuSettings.addAction(self.actionGeneral)
        self.menuSettings.addAction(self.actionPPMS)
        self.menuSettings.addAction(self.actionEmail)
        self.menuSettings.addAction(self.actionFacility)
        self.menuSettings.addAction(self.actionInvoice_template)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autonomous_tab), _translate("MainWindow", "Autonomous sessions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assisted_tab), _translate("MainWindow", "Assisted sessions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.training_tab), _translate("MainWindow", "Training sessions"))
        self.select_btn.setText(_translate("MainWindow", "Select All"))
        self.deselect_btn.setText(_translate("MainWindow", "Deselect All"))
        self.label.setText(_translate("MainWindow", "Send to"))
        self.sendto_combo.setItemText(0, _translate("MainWindow", "Group PI and Admin"))
        self.sendto_combo.setItemText(1, _translate("MainWindow", "Group Admin only"))
        self.copy_chk.setText(_translate("MainWindow", "Copy manager"))
        self.email_button.setText(_translate("MainWindow", "Send Invoices"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionPPMS.setText(_translate("MainWindow", "PPMS"))
        self.actionEmail.setText(_translate("MainWindow", "Email"))
        self.actionInvoice_template.setText(_translate("MainWindow", "Invoice template"))
        self.actionFacility.setText(_translate("MainWindow", "Facility"))
        self.actionGeneral.setText(_translate("MainWindow", "General"))
