# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppms_invoice_client\ui\template.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(462, 651)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.session_chk = QtWidgets.QCheckBox(Dialog)
        self.session_chk.setChecked(True)
        self.session_chk.setObjectName("session_chk")
        self.verticalLayout.addWidget(self.session_chk)
        self.user_chk = QtWidgets.QCheckBox(Dialog)
        self.user_chk.setChecked(True)
        self.user_chk.setObjectName("user_chk")
        self.verticalLayout.addWidget(self.user_chk)
        self.type_chk = QtWidgets.QCheckBox(Dialog)
        self.type_chk.setChecked(True)
        self.type_chk.setObjectName("type_chk")
        self.verticalLayout.addWidget(self.type_chk)
        self.system_chk = QtWidgets.QCheckBox(Dialog)
        self.system_chk.setChecked(True)
        self.system_chk.setObjectName("system_chk")
        self.verticalLayout.addWidget(self.system_chk)
        self.date_chk = QtWidgets.QCheckBox(Dialog)
        self.date_chk.setChecked(True)
        self.date_chk.setObjectName("date_chk")
        self.verticalLayout.addWidget(self.date_chk)
        self.start_chk = QtWidgets.QCheckBox(Dialog)
        self.start_chk.setChecked(True)
        self.start_chk.setObjectName("start_chk")
        self.verticalLayout.addWidget(self.start_chk)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.booked_chk = QtWidgets.QCheckBox(Dialog)
        self.booked_chk.setChecked(True)
        self.booked_chk.setObjectName("booked_chk")
        self.verticalLayout_3.addWidget(self.booked_chk)
        self.used_chk = QtWidgets.QCheckBox(Dialog)
        self.used_chk.setObjectName("used_chk")
        self.verticalLayout_3.addWidget(self.used_chk)
        self.notes_chk = QtWidgets.QCheckBox(Dialog)
        self.notes_chk.setObjectName("notes_chk")
        self.verticalLayout_3.addWidget(self.notes_chk)
        self.init_amount_chk = QtWidgets.QCheckBox(Dialog)
        self.init_amount_chk.setObjectName("init_amount_chk")
        self.verticalLayout_3.addWidget(self.init_amount_chk)
        self.fees_chk = QtWidgets.QCheckBox(Dialog)
        self.fees_chk.setObjectName("fees_chk")
        self.verticalLayout_3.addWidget(self.fees_chk)
        self.final_amount_chk = QtWidgets.QCheckBox(Dialog)
        self.final_amount_chk.setChecked(True)
        self.final_amount_chk.setObjectName("final_amount_chk")
        self.verticalLayout_3.addWidget(self.final_amount_chk)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.message_text = QtWidgets.QPlainTextEdit(Dialog)
        self.message_text.setObjectName("message_text")
        self.verticalLayout_2.addWidget(self.message_text)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.template_ok = QtWidgets.QPushButton(Dialog)
        self.template_ok.setObjectName("template_ok")
        self.horizontalLayout.addWidget(self.template_ok)
        self.template_cancel = QtWidgets.QPushButton(Dialog)
        self.template_cancel.setObjectName("template_cancel")
        self.horizontalLayout.addWidget(self.template_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Invoice Template Settings"))
        self.label_2.setText(_translate("Dialog", "Invoice columns"))
        self.session_chk.setText(_translate("Dialog", "Session"))
        self.user_chk.setText(_translate("Dialog", "User"))
        self.type_chk.setText(_translate("Dialog", "Type"))
        self.system_chk.setText(_translate("Dialog", "System"))
        self.date_chk.setText(_translate("Dialog", "Date"))
        self.start_chk.setText(_translate("Dialog", "Start time"))
        self.booked_chk.setText(_translate("Dialog", "Booked time (minutes)"))
        self.used_chk.setText(_translate("Dialog", "Used time (minutes)"))
        self.notes_chk.setText(_translate("Dialog", "Notes"))
        self.init_amount_chk.setText(_translate("Dialog", "Initial Amount"))
        self.fees_chk.setText(_translate("Dialog", "Fees"))
        self.final_amount_chk.setText(_translate("Dialog", "Final Amount"))
        self.label.setText(_translate("Dialog", "Message"))
        self.label_3.setText(_translate("Dialog", "Instructions:"))
        self.label_5.setText(_translate("Dialog", "MONTH  - The month the sessions took place"))
        self.label_6.setText(_translate("Dialog", "YEAR      - The year the sessions took place."))
        self.label_10.setText(_translate("Dialog", "F_NAME - The name of the facility."))
        self.label_7.setText(_translate("Dialog", "F_EMAIL - The facility email address."))
        self.label_9.setText(_translate("Dialog", "M_NAME - The name of the facility manager."))
        self.label_8.setText(_translate("Dialog", "M_MAIL  - The facility manager email address."))
        self.message_text.setPlainText(_translate("Dialog", "This is a summary of charges for use of the F_NAME for MONTH YEAR. Please check that the grant code information is correct; if you wish to make changes please let me know within 7 days. If the information is correct you do not need to take any further action, the charges will be sent to finance for processing.\n"
"\n"
"Please note that email cannot be received at the address \"F_EMAIL\". If you have any questions or queries please do not hesitate to contact M_EMAIL.\n"
"\n"
"Kind regards,\n"
"\n"
"M_NAME"))
        self.template_ok.setText(_translate("Dialog", "OK"))
        self.template_cancel.setText(_translate("Dialog", "Cancel"))
